name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: poestatustest
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
        - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - run: make install-go deps
    - name: CI
      run: make clean test
      env:
        SKIP_PING: yes
        TEST_DATABASE_URL: postgres://postgres:password@postgres:${{ job.services.postgres.ports[5432] }}/poestatustest?sslmode=disable
