name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: poestatustest
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dbpass
        ports:
          - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - run: go version
      - run: make deps
      - run: env PATH=$PATH:$(go env GOPATH)/bin make clean test build-binaries
        env:
          SKIP_PING: yes
          TEST_DATABASE_URL: postgres://postgres:dbpass@localhost:5432/poestatustest?sslmode=disable
