name: Scan

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - run: go version
      - run: make deps build-binaries
      - run: cd ./cmd/poe-status-client && ./poe-status-client --url 'http://poe-status.com'
        env:
          MAIN_TOKEN: ${{ secrets.MAIN_TOKEN }}
